import Head from 'next/head'

export default function CustomHead() {
  return (  
    <Head>
      <title>Grimace Coin</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link href="https://fonts.googleapis.com/css?family=Montserrat:700" />
      <link rel="icon" href="/assets/imgs/favicon.png" />
    </Head>
  );
  }
  